apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: kasperapptimia/guestbook:nginx
        ports:
        - name: nginx-port
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /nginx-health-check
            port: nginx-port
          failureThreshold: 1
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /nginx-health-check
            port: nginx-port
          failureThreshold: 30
          periodSeconds: 10
      imagePullSecrets:
      - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
