FROM python:3.7.3

RUN apt-get update && \
    apt-get install -y binutils libproj-dev

COPY ./requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip install -r requirements.txt
COPY . /app

VOLUME /app/media
VOLUME /app/static

EXPOSE 8000

ENTRYPOINT ["gunicorn"]
CMD ["--workers", "1", "--bind", ":8000", "--log-level", "INFO", \
     "guestbook_backend.wsgi:application"]
